name: 'Cleanup Environment'
description: 'Destroys the environment and uploads test artifacts'

runs:
  using: "composite"
  steps:
    - name: Destroy environment
      run: pnpm run destroy:ci
      shell: bash
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30