name: "Cleanup Environment"
description: "Destroys the environment and uploads test artifacts"

runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: examples/e2e-tests/playwright-report/
        retention-days: 30
      if: ${{ !cancelled() }}
