name: "Setup Environment"
description: "Sets up Node.js, PNPM, AWS credentials, and builds cdk-nextjs"

inputs:
  aws_account:
    description: "AWS account ID"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
    - uses: aws-actions/configure-aws-credentials@v4.2.1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ inputs.aws_account }}:role/GitHubActionRole
    - name: Install dependencies and build cdk-nextjs
      shell: bash
      run: pnpm i && pnpm bundle && pnpm compile
    - name: Install examples dependencies
      shell: bash
      run: cd examples && pnpm i && cd e2e-tests && pnpm install-browser
