// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import * as path from 'path';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for SignFnUrlFunction
 */
export interface SignFnUrlFunctionProps extends cloudfront.experimental.EdgeFunctionProps {
}

/**
 * An AWS Lambda function which executes src/lambdas/sign-fn-url/sign-fn-url.
 */
export class SignFnUrlFunction extends cloudfront.experimental.EdgeFunction {
  constructor(scope: Construct, id: string, props?: SignFnUrlFunctionProps) {
    super(scope, id, {
      description: 'src/lambdas/sign-fn-url/sign-fn-url.edge-lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambdas/sign-fn-url/sign-fn-url.edge-lambda')),
    });
  }
}