// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_ec2, aws_efs, aws_lambda, aws_s3 } from 'aws-cdk-lib';
import type { NextjsType } from '../';

/**
 * OptionalNextjsAssetsDeploymentProps
 */
export interface OptionalNextjsAssetsDeploymentProps {
  /**
   * Required for `NextjsType.GlobalFunctions` and `NextjsType.GlobalContainers`.
   * @stability stable
   */
  readonly staticAssetsBucket?: aws_s3.Bucket;
  /**
   * @stability stable
   */
  readonly relativePathToWorkspace?: string;
  /**
   * @default true
   * @stability stable
   */
  readonly debug?: boolean;
  /**
   * Prefix to the URI path the app will be served at.
   * @stability stable
   */
  readonly basePath?: string;
  /**
   * @stability stable
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
  /**
   * @stability stable
   */
  readonly dockerImageCode?: aws_lambda.DockerImageCode;
  /**
   * @stability stable
   */
  readonly containerMountPathForEfs?: string;
  /**
   * @stability stable
   */
  readonly buildImageDigest?: string;
  /**
   * @stability stable
   */
  readonly accessPoint?: aws_efs.AccessPoint;
}
