// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { NextjsType } from '../';

/**
 * OptionalNextjsBuildProps
 */
export interface OptionalNextjsBuildProps {
  /**
   * @stability stable
   */
  readonly skipBuild?: boolean;
  /**
   * @stability stable
   */
  readonly relativePathToPackage?: string;
  /**
   * @stability stable
   */
  readonly buildCommand?: string;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
  /**
   * Directory where the Next.js application is located for local builds. This should contain the package.json and Next.js application files.
   * @stability stable
   */
  readonly buildDirectory?: string;
}
