// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_cloudfront, aws_ec2, aws_efs, aws_s3 } from 'aws-cdk-lib';

/**
 * OptionalNextjsPostDeployProps
 */
export interface OptionalNextjsPostDeployProps {
  /**
   * Required for `NextjsType.GlobalFunctions` and `NextjsType.GlobalContainers`.
   * @stability stable
   */
  readonly staticAssetsBucket?: aws_s3.Bucket;
  /**
   * @stability stable
   */
  readonly relativePathToPackage?: string;
  /**
   * CloudFront Distribution to invalidate.
   * @stability stable
   */
  readonly distribution?: aws_cloudfront.IDistribution;
  /**
   * If true, logs details in custom resource lambda.
   * @default true
   * @stability stable
   */
  readonly debug?: boolean;
  /**
   * @stability stable
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * @stability stable
   */
  readonly buildImageDigest?: string;
  /**
   * @stability stable
   */
  readonly buildId?: string;
  /**
   * @stability stable
   */
  readonly accessPoint?: aws_efs.AccessPoint;
}
