// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_cloudfront, aws_dynamodb, aws_s3 } from 'aws-cdk-lib';

/**
 * OptionalNextjsPostDeployProps
 */
export interface OptionalNextjsPostDeployProps {
  /**
   * Required for `NextjsType.GlobalFunctions` and `NextjsType.GlobalContainers`.
   * @stability stable
   */
  readonly staticAssetsBucket?: aws_s3.Bucket;
  /**
   * DynamoDB table for cleaning up old BUILD_ID prefixed revalidation entries.
   * @stability stable
   */
  readonly revalidationTable?: aws_dynamodb.TableV2;
  /**
   * @stability stable
   */
  readonly relativePathToPackage?: string;
  /**
   * CloudFront Distribution to invalidate.
   * @stability stable
   */
  readonly distribution?: aws_cloudfront.IDistribution;
  /**
   * If true, logs details in custom resource lambda.
   * @default true
   * @stability stable
   */
  readonly debug?: boolean;
  /**
   * Cache bucket for cleaning up old BUILD_ID prefixed objects.
   * @stability stable
   */
  readonly cacheBucket?: aws_s3.IBucket;
  /**
   * @stability stable
   */
  readonly buildId?: string;
}
