// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_ec2 } from 'aws-cdk-lib';

/**
 * OptionalNextjsFileSystemProps
 */
export interface OptionalNextjsFileSystemProps {
  /**
   * @stability stable
   */
  readonly vpc?: aws_ec2.IVpc;
}
