// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { NextjsFunctionGroupRoutes, NextjsType } from '../';

/**
 * OptionalNextjsBuildProps
 */
export interface OptionalNextjsBuildProps {
  /**
   * @stability stable
   */
  readonly skipBuild?: boolean;
  /**
   * Route groups to package into separate Lambda functions.
   * Only the two
   * Functions `NextjsType`s pass this; see `NextjsFunctionGroup`.
   * @stability stable
   */
  readonly functionGroups?: Array<NextjsFunctionGroupRoutes>;
  /**
   * @stability stable
   */
  readonly buildCommand?: string;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
  /**
   * Directory where the Next.js application is located for local builds. This should contain the package.json and Next.js application files.
   * @stability stable
   */
  readonly buildDirectory?: string;
}
