// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { NextjsInvalidationOverrides } from '../';
import type { aws_cloudfront } from 'aws-cdk-lib';

/**
 * OptionalNextjsInvalidationProps
 */
export interface OptionalNextjsInvalidationProps {
  /**
   * Override props for every construct.
   * @stability stable
   */
  readonly overrides?: NextjsInvalidationOverrides;
  /**
   * CloudFront Distribution to invalidate.
   * @stability stable
   */
  readonly distribution?: aws_cloudfront.IDistribution;
}
