// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_ec2, aws_ecs } from 'aws-cdk-lib';

/**
 * OptionalClusterProps
 */
export interface OptionalClusterProps {
  /**
   * The VPC where your ECS instances will be running or your ENIs will be deployed.
   * @default - creates a new VPC with two AZs
   * @stability stable
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * Encryption configuration for ECS Managed storage.
   * @default - no encryption will be applied.
   * @stability stable
   */
  readonly managedStorageConfiguration?: aws_ecs.ManagedStorageConfiguration;
  /**
   * The execute command configuration for the cluster.
   * @default - no configuration will be provided.
   * @stability stable
   */
  readonly executeCommandConfiguration?: aws_ecs.ExecuteCommandConfiguration;
  /**
   * Whether to enable Fargate Capacity Providers.
   * @default false
   * @stability stable
   */
  readonly enableFargateCapacityProviders?: boolean;
  /**
   * The service discovery namespace created in this cluster.
   * @default - no service discovery namespace created, you can use `addDefaultCloudMapNamespace` to add a
default service discovery namespace later.
   * @stability stable
   */
  readonly defaultCloudMapNamespace?: aws_ecs.CloudMapNamespaceOptions;
  /**
   * If true CloudWatch Container Insights will be enabled for the cluster.
   * @default - Container Insights will be disabled for this cluster.
   * @stability stable
   */
  readonly containerInsights?: boolean;
  /**
   * The name for the cluster.
   * @default CloudFormation-generated name
   * @stability stable
   */
  readonly clusterName?: string;
  /**
   * The ec2 capacity to add to the cluster.
   * @default - no EC2 capacity will be added, you can use `addCapacity` to add capacity later.
   * @stability stable
   */
  readonly capacity?: aws_ecs.AddCapacityOptions;
}
