// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_dynamodb, aws_s3 } from 'aws-cdk-lib';
import type { NextjsType } from '../';

/**
 * OptionalNextjsFunctionsProps
 */
export interface OptionalNextjsFunctionsProps {
  /**
   * Key prefix the assets were uploaded under, so the image optimizer can rebuild the same keys.
   * @stability stable
   */
  readonly staticAssetsKeyPrefix?: string;
  /**
   * S3 bucket holding `.next/static` and `public`. Both deployment styles need it: the runtime's image optimizer fetches the bytes of every non-absolute `<Image>` from S3, since they are deliberately not in the deployment package, and on every type but `NextjsRegionalContainers` so does a rewrite that lands on a `public/` file. Read access is scoped to `staticAssetsKeyPrefix`.
   * @stability stable
   */
  readonly staticAssetsBucket?: aws_s3.IBucket;
  /**
   * DynamoDB table for revalidation metadata.
   * @stability stable
   */
  readonly revalidationTable?: aws_dynamodb.ITableV2;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
  /**
   * S3 bucket for cache storage.
   * @stability stable
   */
  readonly cacheBucket?: aws_s3.IBucket;
  /**
   * Build ID for cache key prefixing.
   * @stability stable
   */
  readonly buildId?: string;
}
