// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".

/**
 * OptionalPostDeployCustomResourceProperties
 */
export interface OptionalPostDeployCustomResourceProperties {
  /**
   * @stability stable
   */
  readonly staticAssetsBucketName?: string;
  /**
   * @default {
   distributionId: this.props.distribution?.distributionId,
   invalidationBatch: {
     callerReference: new Date().toISOString(),
     paths: {
       quantity: 1,
       items: ["/*"], // invalidate all paths
     },
   },
 }
   * @stability stable
   */
  readonly createInvalidationCommandInput?: Record<string, any>;
  /**
   * Time to live in milliseconds.
   * Must be string because of CloudFormation Custom Resource limitation
   * @default (1000 * 60 * 60 * 24 * 30).toString()
   * @stability stable
   */
  readonly msTtl?: string;
  /**
   * @stability stable
   */
  readonly buildImageDigest?: string;
  /**
   * Build ID of current deployment.
   * Used to prune FileSystem of directories
   * with old build ids and prune S3 based on metadat and `msTtl`
   * @stability stable
   */
  readonly buildId?: string;
}
