// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".

/**
 * OptionalPostDeployCustomResourceProperties
 */
export interface OptionalPostDeployCustomResourceProperties {
  /**
   * @stability stable
   */
  readonly staticAssetsBucketName?: string;
  /**
   * DynamoDB revalidation table name for cleaning up old BUILD_ID prefixed entries.
   * @stability stable
   */
  readonly revalidationTableName?: string;
  /**
   * @default {
   distributionId: this.props.distribution?.distributionId,
   invalidationBatch: {
     callerReference: new Date().toISOString(),
     paths: {
       quantity: 1,
       items: ["/*"], // invalidate all paths
     },
   },
 }
   * @stability stable
   */
  readonly createInvalidationCommandInput?: Record<string, any>;
  /**
   * Cache bucket name for cleaning up old BUILD_ID prefixed objects.
   * @stability stable
   */
  readonly cacheBucketName?: string;
  /**
   * Time to live in milliseconds.
   * Must be string because of CloudFormation Custom Resource limitation
   * @default (1000 * 60 * 60 * 24 * 30).toString()
   * @stability stable
   */
  readonly msTtl?: string;
  /**
   * Build ID of current deployment.
   * Used to prune cache bucket of objects
   * with old build ids, prune DynamoDB revalidation entries with old build ids,
   * and prune S3 static assets based on metadata and `msTtl`
   * @stability stable
   */
  readonly buildId?: string;
}
