// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_dynamodb, aws_s3 } from "aws-cdk-lib";

/**
 * OptionalNextjsCacheProps
 */
export interface OptionalNextjsCacheProps {
  /**
   * Bring your own DynamoDB table for revalidation metadata.
   * When provided,
   * cdk-nextjs will skip creating a new table. The table must have `pk` (String)
   * as partition key and `sk` (String) as sort key. Entries are partitioned by
   * `buildId` so multiple deployments can safely share one table.
   * @stability stable
   */
  readonly revalidationTable?: aws_dynamodb.ITableV2;
  /**
   * Bring your own S3 bucket for cache storage.
   * When provided, cdk-nextjs
   * will skip creating a new bucket. Cache objects are prefixed with `buildId`
   * so multiple deployments can safely share one bucket.
   * @stability stable
   */
  readonly cacheBucket?: aws_s3.IBucket;
  /**
   * Absolute path to the init cache directory.
   * @stability stable
   */
  readonly initCacheDir?: string;
  /**
   * @stability stable
   */
  readonly buildId?: string;
}
