// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_dynamodb, aws_ec2, aws_s3 } from 'aws-cdk-lib';
import type { NextjsType } from '../';

/**
 * OptionalNextjsContainersProps
 */
export interface OptionalNextjsContainersProps {
  /**
   * VPC is required for container deployments.
   * Containers need VPC for networking.
   * @stability stable
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * @stability stable
   */
  readonly relativeEntrypointPath?: string;
  /**
   * Relative path from buildDirectory to the package containing Next.js app.
   * @stability stable
   */
  readonly relativePathToPackage?: string;
  /**
   * DynamoDB table for revalidation metadata.
   * @stability stable
   */
  readonly revalidationTable?: aws_dynamodb.TableV2;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
  /**
   * @stability stable
   */
  readonly healthCheckPath?: string;
  /**
   * S3 bucket for cache storage.
   * @stability stable
   */
  readonly cacheBucket?: aws_s3.IBucket;
  /**
   * Build ID for cache key prefixing.
   * @stability stable
   */
  readonly buildId?: string;
  /**
   * Directory where the Next.js application is located. This should contain the .next directory and other build artifacts. Required for local builds.
   * @stability stable
   */
  readonly buildDirectory?: string;
}
