// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { NextjsFunctionGroupRoutes, NextjsType } from '../';
import type { aws_lambda } from 'aws-cdk-lib';

/**
 * OptionalNextjsBuildProps
 */
export interface OptionalNextjsBuildProps {
  /**
   * @stability stable
   */
  readonly skipBuild?: boolean;
  /**
   * Route groups to package into separate Lambda functions.
   * Only the two
   * Functions `NextjsType`s pass this; see `NextjsFunctionGroup`.
   * @stability stable
   */
  readonly functionGroups?: Array<NextjsFunctionGroupRoutes>;
  /**
   * @stability stable
   */
  readonly buildCommand?: string;
  /**
   * Lambda architecture the Functions types deploy, which decides the `sharp` binaries staged into every deployment root.
   * Ignored by the Containers
   * types, whose image is built for the synth machine.
   * @default - the architecture of the machine running synth
   * @stability stable
   */
  readonly architecture?: aws_lambda.Architecture;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
  /**
   * Directory where the Next.js application is located for local builds. This should contain the package.json and Next.js application files.
   * @stability stable
   */
  readonly buildDirectory?: string;
}
