// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".

/**
 * OptionalNextjsCacheProps
 */
export interface OptionalNextjsCacheProps {
  /**
   * @stability stable
   */
  readonly buildId?: string;
}
