// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_cloudfront, aws_dynamodb, aws_s3 } from 'aws-cdk-lib';

/**
 * OptionalNextjsPostDeployProps
 */
export interface OptionalNextjsPostDeployProps {
  /**
   * S3 key prefix the static assets were uploaded under (`NextjsStaticAssets.keyPrefix`). Scopes pruning to this app's objects, so that apps or branches sharing one bucket under different `basePath`s don't prune each other's assets.
   * @stability stable
   */
  readonly staticAssetsKeyPrefix?: string;
  /**
   * Required for `NextjsType.GlobalFunctions` and `NextjsType.GlobalContainers`.
   * @stability stable
   */
  readonly staticAssetsBucket?: aws_s3.IBucket;
  /**
   * DynamoDB table for cleaning up old BUILD_ID prefixed revalidation entries.
   * @stability stable
   */
  readonly revalidationTable?: aws_dynamodb.ITableV2;
  /**
   * CloudFront Distribution to invalidate.
   * @stability stable
   */
  readonly distribution?: aws_cloudfront.IDistribution;
  /**
   * If true, logs details in custom resource lambda.
   * @default true
   * @stability stable
   */
  readonly debug?: boolean;
  /**
   * Cache bucket for cleaning up old BUILD_ID prefixed objects.
   * @stability stable
   */
  readonly cacheBucket?: aws_s3.IBucket;
  /**
   * @stability stable
   */
  readonly buildId?: string;
}
