// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_dynamodb, aws_ecs, aws_elasticloadbalancingv2, aws_s3 } from 'aws-cdk-lib';
import type { NextjsType } from '../';

/**
 * OptionalNextjsContainersProps
 */
export interface OptionalNextjsContainersProps {
  /**
   * Bring your own ECS cluster.
   * When provided, cdk-nextjs will skip creating
   * a new cluster and VPC gateway endpoints. The cluster is passed directly
   * to `ApplicationLoadBalancedFargateService`.
   * @stability stable
   */
  readonly ecsCluster?: aws_ecs.ICluster;
  /**
   * Bring your own Application Load Balancer.
   * When provided, it is passed
   * directly to `ApplicationLoadBalancedFargateService`. If the ALB already
   * has a listener on port 80, call `removeAutoCreatedListener()` after
   * construction to avoid deployment failures.
   * @stability stable
   */
  readonly alb?: aws_elasticloadbalancingv2.IApplicationLoadBalancer;
  /**
   * From the deployment root to the Next.js project dir, POSIX, `""` at the repo root.
   * @stability stable
   */
  readonly relativeProjectDir?: string;
  /**
   * @stability stable
   */
  readonly relativeEntrypointPath?: string;
  /**
   * Path to an API Route Handler that returns HTTP 200, used by the ALB target group and the ECS container health check.
   * Both hit the app directly, so this
   * is the path including the app's `basePath` — the root constructs prefix their
   * own `healthCheckPath` prop with it.
   * @stability stable
   */
  readonly healthCheckPath?: string;
  /**
   * Directory where the Next.js application is located: the Docker build context, holding the `.next` directory and other build artifacts.
   * @stability stable
   */
  readonly buildDirectory?: string;
  /**
   * Key prefix the assets were uploaded under, so the image optimizer can rebuild the same keys.
   * @stability stable
   */
  readonly staticAssetsKeyPrefix?: string;
  /**
   * S3 bucket holding `.next/static` and `public`. On every type but `NextjsRegionalContainers` the runtime reads it: its image optimizer fetches the bytes of every non-absolute `<Image>` from S3, since they are deliberately not in the deployment package, and so does a rewrite that lands on a `public/` file. `NextjsRegionalContainers` carries both in its image, so it gets neither the bucket's environment nor read access to it. Read access is scoped to `staticAssetsKeyPrefix`.
   * @stability stable
   */
  readonly staticAssetsBucket?: aws_s3.IBucket;
  /**
   * DynamoDB table for revalidation metadata.
   * @stability stable
   */
  readonly revalidationTable?: aws_dynamodb.ITableV2;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
  /**
   * S3 bucket for cache storage.
   * @stability stable
   */
  readonly cacheBucket?: aws_s3.IBucket;
  /**
   * Build ID for cache key prefixing.
   * @stability stable
   */
  readonly buildId?: string;
}
