// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_ec2, aws_lambda, aws_s3 } from 'aws-cdk-lib';
import type { PublicDirEntry } from '../';

/**
 * OptionalNextjsApiProps
 */
export interface OptionalNextjsApiProps {
  /**
   * [Future] Required if `NextjsRegionalContainers`.
   * VPC to create VPC Link and ECS Service Discovery
   * @stability stable
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * S3 key prefix the static assets were uploaded under, i.e. `NextjsStaticAssets.keyPrefix`, which namespaces a shared bucket.
   * Independent of `basePath` above: that one is the URL prefix the REST API
   * serves the app at (commonly the API Gateway stage), while this one is where
   * the objects live in the bucket. `_next/static` and public directory
   * requests are mapped to S3 keys directly, so they 404 unless this prefix is
   * applied.
   * @stability stable
   */
  readonly staticAssetsKeyPrefix?: string;
  /**
   * Required if `NextjsRegionalFunctions`.
   * The Lambda function for server-side rendering
   * @stability stable
   */
  readonly serverFunction?: aws_lambda.IFunction;
  /**
   * Deploy the stage again once each stack update has finished, so it serves the API as it is after the update.
   * CloudFormation snapshots the API into a new deployment while resources
   * removed from the template still exist — it deletes them only during
   * cleanup — so the stage keeps serving them. After removing a function
   * group, its routes then point at a deleted Lambda and answer 500 until the
   * next deployment. An EventBridge rule on this stack's `UPDATE_COMPLETE`
   * (and `UPDATE_ROLLBACK_COMPLETE`) invokes a small function that deploys the
   * stage from the live API and deletes the deployments its earlier runs made.
   *
   * Ignored when `overrides.restApiProps.deploy` is `false`: there is no stage.
   * @default true
   * @stability stable
   */
  readonly redeployAfterUpdate?: boolean;
  /**
   * Optional base path for the application.
   * @stability stable
   */
  readonly basePath?: string;
  /**
   * The S3 bucket containing static assets.
   * @stability stable
   */
  readonly staticAssetsBucket?: aws_s3.IBucket;
  /**
   * Path to directory of Next.js app's public directory. Used to add resources to API Gateway REST API for public directory to go directly to S3.
   * @stability stable
   */
  readonly publicDirEntries?: Array<PublicDirEntry>;
}
