// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_certificatemanager, aws_cloudfront, aws_elasticloadbalancingv2, aws_lambda, aws_s3 } from 'aws-cdk-lib';
import type { NextjsDistributionFunctionGroup, NextjsType, PublicDirEntry } from '../';

/**
 * OptionalNextjsDistributionProps
 */
export interface OptionalNextjsDistributionProps {
  /**
   * The app's `next.config` `trailingSlash`. A `trailingSlash` app links to `/pricing/`, which an exact group pattern of `pricing` does not match, so each one needs a slash variant. Ignored without {@link functionGroups}.
   * @default false
   * @stability stable
   */
  readonly trailingSlash?: boolean;
  /**
   * Required if `NextjsType.GLOBAL_CONTAINERS` or `NextjsType.REGIONAL_CONTAINERS`.
   * @stability stable
   */
  readonly loadBalancer?: aws_elasticloadbalancingv2.IApplicationLoadBalancer;
  /**
   * Whether the app has Pages Router routes, and therefore a `/_next/data/<buildId>/…json` URL space that has to be routed alongside the HTML one.
   * Ignored without {@link functionGroups}.
   * @default false
   * @stability stable
   */
  readonly hasDataRoutes?: boolean;
  /**
   * Required if `NextjsType.GLOBAL_FUNCTIONS`.
   * @stability stable
   */
  readonly functionUrl?: aws_lambda.IFunctionUrl;
  /**
   * The non-`default` function groups, each needing its own behaviors so the routes it was packaged with reach it rather than the default function.
   * @default - no splitting; the default behavior serves every dynamic route
   * @stability stable
   */
  readonly functionGroups?: Array<NextjsDistributionFunctionGroup>;
  /**
   * @stability stable
   */
  readonly distribution?: aws_cloudfront.Distribution;
  /**
   * Optional but only applicable for `NextjsType.GLOBAL_CONTAINERS`.
   * @stability stable
   */
  readonly certificate?: aws_certificatemanager.ICertificate;
  /**
   * URI path prefix the app is served at.
   * Surrounding slashes are normalized
   * away, so "/base", "base" and "/base/" all produce the same cache behaviors.
   * @stability stable
   */
  readonly basePath?: string;
  /**
   * The app's own `assetPrefix`.
   * Next.js emits `<assetPrefix>/_next/static/...`
   * for every bundle while the objects stay at `<basePath>/_next/static/...` in
   * S3, so the prefix's path gets a cache behavior of its own that rewrites it
   * away.
   *
   * Either form is accepted: a path ("/cdn"), or an absolute URL, in which case
   * only its path counts ("https://cdn.example.com/cdn" behaves as "/cdn", and
   * "https://cdn.example.com" needs no behavior at all). An absolute prefix's path
   * matters because `next build` compiles a `/cdn/_next/:path+` rewrite of its
   * own, so `next start` serves every bundle under it — a CDN fronting this
   * distribution there has to be answered too.
   *
   * Applied on top of `basePath`, not under it, because that is how Next.js
   * builds the URL.
   * @default - read from the build's `required-server-files.json`
   * @stability stable
   */
  readonly assetPrefix?: string;
  /**
   * Entries (files/directories) within Next.js app's public directory. Used to add static behaviors to distribution.
   * @stability stable
   */
  readonly publicDirEntries?: Array<PublicDirEntry>;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
  /**
   * Bucket containing static assets.
   * Must be provided if you want to serve static files.
   * @stability stable
   */
  readonly assetsBucket?: aws_s3.IBucket;
}
