// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_lambda, Duration } from 'aws-cdk-lib';

/**
 * OptionalAliasProps
 */
export interface OptionalAliasProps {
  /**
   * Name of this alias.
   * @stability stable
   */
  readonly aliasName?: string;
  /**
   * Specifies a provisioned concurrency configuration for a function's alias.
   * @default No provisioned concurrency
   * @stability stable
   */
  readonly provisionedConcurrentExecutions?: number;
  /**
   * Description for the alias.
   * @default No description
   * @stability stable
   */
  readonly description?: string;
  /**
   * Additional versions with individual weights this alias points to.
   * Individual additional version weights specified here should add up to
   * (less than) one. All remaining weight is routed to the default
   * version.
   *
   * For example, the config is
   *
   *    version: "1"
   *    additionalVersions: [{ version: "2", weight: 0.05 }]
   *
   * Then 5% of traffic will be routed to function version 2, while
   * the remaining 95% of traffic will be routed to function version 1.
   * @default No additional versions
   * @stability stable
   */
  readonly additionalVersions?: Array<aws_lambda.VersionWeight>;
  /**
   * The maximum number of times to retry when the function returns an error.
   * Minimum: 0
   * Maximum: 2
   * @default 2
   * @stability stable
   */
  readonly retryAttempts?: number;
  /**
   * The destination for successful invocations.
   * @default - no destination
   * @stability stable
   */
  readonly onSuccess?: aws_lambda.IDestination;
  /**
   * The destination for failed invocations.
   * @default - no destination
   * @stability stable
   */
  readonly onFailure?: aws_lambda.IDestination;
  /**
   * The maximum age of a request that Lambda sends to a function for processing.
   * Minimum: 60 seconds
   * Maximum: 6 hours
   * @default Duration.hours(6)
   * @stability stable
   */
  readonly maxEventAge?: Duration;
}
