// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { NextjsDistributionOverrides, NextjsType, PublicDirEntry } from '../';
import type { aws_certificatemanager, aws_cloudfront, aws_s3 } from 'aws-cdk-lib';

/**
 * OptionalNextjsDistributionProps
 */
export interface OptionalNextjsDistributionProps {
  /**
   * Override props for every construct.
   * @stability stable
   */
  readonly overrides?: NextjsDistributionOverrides;
  /**
   * Required if `NextjsType.GLOBAL_FUNCTIONS`.
   * @stability stable
   */
  readonly functionArn?: string;
  /**
   * @stability stable
   */
  readonly distribution?: aws_cloudfront.Distribution;
  /**
   * Optional but only applicable for `NextjsType.GLOBAL_CONTAINERS`.
   * @stability stable
   */
  readonly certificate?: aws_certificatemanager.ICertificate;
  /**
   * @stability stable
   */
  readonly basePath?: string;
  /**
   * Path to directory of Next.js app's public directory. Used to add static behaviors to distribution.
   * @stability stable
   */
  readonly publicDirEntries?: Array<PublicDirEntry>;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
  /**
   * Dynamic (Next.js server) URL to add behavior to distribution.
   * @stability stable
   */
  readonly dynamicUrl?: string;
  /**
   * Bucket containing static assets.
   * Must be provided if you want to serve static files.
   * @stability stable
   */
  readonly assetsBucket?: aws_s3.IBucket;
}
