// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_ec2 } from 'aws-cdk-lib';
import type { NextjsType } from '../';

/**
 * OptionalNextjsVpcProps
 */
export interface OptionalNextjsVpcProps {
  /**
   * Bring your own VPC.
   * @stability stable
   */
  readonly vpc?: aws_ec2.IVpc;
  /**
   * @stability stable
   */
  readonly nextjsType?: NextjsType;
}
