// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import type { aws_lambda } from 'aws-cdk-lib';

/**
 * OptionalFunctionUrlProps
 */
export interface OptionalFunctionUrlProps {
  /**
   * The function to which this url refers.
   * It can also be an `Alias` but not a `Version`.
   * @stability stable
   */
  readonly function?: aws_lambda.IFunction;
  /**
   * The type of invocation mode that your Lambda function uses.
   * @default InvokeMode.BUFFERED
   * @stability stable
   */
  readonly invokeMode?: aws_lambda.InvokeMode;
  /**
   * The cross-origin resource sharing (CORS) settings for your function URL.
   * @default - No CORS configuration.
   * @stability stable
   */
  readonly cors?: aws_lambda.FunctionUrlCorsOptions;
  /**
   * The type of authentication that your function URL uses.
   * @default FunctionUrlAuthType.AWS_IAM
   * @stability stable
   */
  readonly authType?: aws_lambda.FunctionUrlAuthType;
}
