import { test, expect } from "@playwright/test";
import { waitXSec } from "./utils/wait-5-sec";
import {
  waitForFreshTimestamp,
  waitForSettledTimestamp,
} from "./utils/wait-for-fresh-timestamp";
import { getPageTimestamp } from "./utils/timestamp-helpers";

/**
 * The on-demand tests run against `/isr-on-demand/[id]`, not `/isr/[id]`: the
 * latter also regenerates every 10 seconds on its own, so its timestamp changing
 * would pass even if `revalidateTag` did nothing. The former only goes stale
 * after 30 days (`cacheLife('max')`), so within a test only an on-demand
 * revalidation can change it - which the first test below checks directly.
 */
const ON_DEMAND = "./isr-on-demand";
/** `/api/revalidate`'s query for revalidating the on-demand route by tag only. */
const BY_TAG = "collection=on-demand";

test.describe("revalidation", () => {
  test("on-demand page does not regenerate without a revalidation", async ({
    page,
    baseURL,
  }) => {
    // no cache in dev mode
    test.skip(baseURL?.includes("localhost") === true);

    // The control for the tests below: if this page regenerated by itself, their
    // timestamps changing would prove nothing. Settle first, since an earlier
    // test's revalidation may still be landing.
    await page.goto(`${ON_DEMAND}/3`, { waitUntil: "networkidle" });
    const settled = await waitForSettledTimestamp(page, { intervalMs: 1_000 });
    expect(settled).toBeTruthy();

    // Longer than `/isr/[id]`'s 10-second revalidate, so that route would have
    // regenerated by now.
    await waitXSec(15);
    await page.reload({ waitUntil: "networkidle" });
    expect(await getPageTimestamp(page)).toBe(settled);
  });

  test("should revalidate ISR page when calling revalidate API", async ({
    page,
    baseURL,
  }) => {
    // no cache in dev mode
    test.skip(baseURL?.includes("localhost") === true);

    // Step 1: Visit ISR page and record initial timestamp
    await page.goto(`${ON_DEMAND}/1`, { waitUntil: "networkidle" });
    const initialTimestamp = await getPageTimestamp(page);
    expect(initialTimestamp).toBeTruthy();
    console.log(`Initial ISR page timestamp: ${initialTimestamp}`);

    // Step 2: Wait a moment to ensure timestamp difference
    await waitXSec(2);

    // Step 3: Call revalidation API to invalidate cache
    // Tag only: the API's default `path` is `/isr/[id]`, a different route.
    console.log("Calling /api/revalidate to invalidate 'on-demand' tag...");
    const revalidateResponse = await page.goto(`./api/revalidate?${BY_TAG}`, {
      waitUntil: "networkidle",
    });
    expect(revalidateResponse?.status()).toBe(200);
    const revalidateData = await revalidateResponse?.json();
    expect(revalidateData).toMatchObject({
      revalidated: true,
      cache: "no-store",
    });
    console.log("Revalidation API called successfully");

    // Step 4: Visit ISR page again - poll until fresh, since CloudFront
    // invalidation and cross-instance cache eviction are eventually
    // consistent with no fixed completion time.
    await page.goto(`${ON_DEMAND}/1`, { waitUntil: "networkidle" });
    const revalidatedTimestamp = await waitForFreshTimestamp(
      page,
      initialTimestamp,
    );
    console.log(`After revalidation: ${revalidatedTimestamp}`);

    // Verify the page was freshly rendered. Not asserting recency: the
    // timestamp reflects server regeneration time, which can precede this
    // check by longer than any fixed window under slow CDN invalidation
    // propagation - the content changing at all is the meaningful signal.
    expect(revalidatedTimestamp).not.toBe(initialTimestamp);

    console.log("✓ Revalidation successfully triggered fresh render");
  });

  test("should revalidate multiple ISR pages with same tag", async ({
    page,
    baseURL,
  }) => {
    // no cache in dev mode
    test.skip(baseURL?.includes("localhost") === true);

    // Visit multiple ISR pages that use the same 'on-demand' tag
    const posts = [1, 2, 3];
    const initialTimestamps: Map<number, string> = new Map();

    // Step 1: Visit all pages and record settled timestamps. Settled, not the
    // first thing served: the previous test's revalidation of the same tag may
    // still be landing, and would otherwise pass this one on its own.
    for (const postId of posts) {
      await page.goto(`${ON_DEMAND}/${postId}`, { waitUntil: "networkidle" });
      const timestamp = await waitForSettledTimestamp(page, {
        intervalMs: 1_000,
      });
      expect(timestamp).toBeTruthy();
      initialTimestamps.set(postId, timestamp!);
      console.log(`Post ${postId} initial: ${timestamp}`);
    }

    // Step 2: Wait and call revalidation API
    await waitXSec(2);
    console.log("Revalidating 'on-demand' tag for all posts...");
    const revalidateResponse = await page.goto(`./api/revalidate?${BY_TAG}`, {
      waitUntil: "networkidle",
    });
    expect(revalidateResponse?.status()).toBe(200);
    expect(await revalidateResponse?.json()).toMatchObject({
      revalidated: true,
    });

    // Step 3: Check all pages were revalidated. Poll until fresh, since
    // CloudFront invalidation and cross-instance cache eviction are
    // eventually consistent with no fixed completion time.
    for (const postId of posts) {
      await page.goto(`${ON_DEMAND}/${postId}`, { waitUntil: "networkidle" });
      const timestamp = await waitForFreshTimestamp(
        page,
        initialTimestamps.get(postId) ?? null,
      );

      console.log(`Post ${postId} after revalidation: ${timestamp}`);

      // Should have a different (newer) timestamp
      expect(timestamp).not.toBe(initialTimestamps.get(postId));
    }

    console.log("✓ All pages with 'on-demand' tag were revalidated");
  });

  test("should handle revalidation with custom path parameter", async ({
    page,
    baseURL,
  }) => {
    // no cache in dev mode
    test.skip(baseURL?.includes("localhost") === true);

    // Visit a specific ISR page
    await page.goto(`${ON_DEMAND}/2`, { waitUntil: "networkidle" });
    const initialTimestamp = await getPageTimestamp(page);
    console.log(`Initial: ${initialTimestamp}`);

    await waitXSec(2);

    // Call revalidation with custom path parameter. The API always calls
    // `revalidateTag` as well, so give it a tag this route does not carry:
    // `revalidatePath` is then the only thing that can refresh it.
    console.log("Calling revalidate API with custom path...");
    const response = await page.goto(
      "./api/revalidate?path=/isr-on-demand/[id]&collection=unused-by-any-route",
      { waitUntil: "networkidle" },
    );
    expect(response?.status()).toBe(200);

    // Verify revalidation worked. Poll until fresh, since CloudFront
    // invalidation and cross-instance cache eviction are eventually
    // consistent with no fixed completion time.
    await page.goto(`${ON_DEMAND}/2`, { waitUntil: "networkidle" });
    const revalidatedTimestamp = await waitForFreshTimestamp(
      page,
      initialTimestamp,
    );
    console.log(`After revalidation: ${revalidatedTimestamp}`);

    expect(revalidatedTimestamp).not.toBe(initialTimestamp);

    console.log("✓ Custom path revalidation successful");
  });

  test("should return proper response from revalidate API", async ({
    page,
    baseURL,
  }) => {
    // no cache in dev mode
    test.skip(baseURL?.includes("localhost") === true);

    // Test the revalidate API response structure
    const response = await page.goto("./api/revalidate", {
      waitUntil: "networkidle",
    });

    expect(response?.status()).toBe(200);

    const data = await response?.json();
    expect(data).toHaveProperty("revalidated");
    expect(data).toHaveProperty("now");
    expect(data).toHaveProperty("cache");

    expect(data.revalidated).toBe(true);
    expect(data.cache).toBe("no-store");
    expect(typeof data.now).toBe("number");
    expect(data.now).toBeGreaterThan(0);

    console.log("✓ Revalidate API response structure is correct:", data);
  });

  test("should maintain cache within revalidation period", async ({
    page,
    baseURL,
  }) => {
    // no cache in dev mode
    test.skip(baseURL?.includes("localhost") === true);

    // Step 1: Trigger fresh render by revalidating
    await page.goto("./api/revalidate?collection=collection", {
      waitUntil: "networkidle",
    });
    await waitXSec(5);

    // Step 2: Visit page to create fresh cache entry. Poll until two loads
    // agree rather than trusting the first one: `waitXSec(5)` above only lets
    // the *invalidation* land, and the re-render happens on the next request -
    // so the first load can legitimately serve the expired entry and kick off
    // the background revalidation whose result the reload below then sees.
    // Settling first is what makes step 3 an assertion about caching instead of
    // an assertion that revalidation is slow.
    await page.goto("./isr/1", { waitUntil: "networkidle" });
    const firstTimestamp = await waitForSettledTimestamp(page, {
      intervalMs: 1_000,
    });
    console.log(`First visit: ${firstTimestamp}`);

    // Step 3: Immediately reload - should serve from cache (same timestamp)
    await page.reload({ waitUntil: "networkidle" });
    const cachedTimestamp = await getPageTimestamp(page);
    console.log(`Cached visit: ${cachedTimestamp}`);

    // Should be identical timestamp
    expect(cachedTimestamp).toBe(firstTimestamp);

    console.log("✓ Cache maintained within revalidation period");
  });
});
