// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for RedeployStageFunction
 */
export interface RedeployStageFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambdas/redeploy-stage/redeploy-stage.
 */
export class RedeployStageFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: RedeployStageFunctionProps) {
    super(scope, id, {
      description: 'src/lambdas/redeploy-stage/redeploy-stage.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambdas/redeploy-stage/redeploy-stage.lambda')),
    });
  }
}