// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for RevalidateFunction
 */
export interface RevalidateFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambdas/revalidate/revalidate.
 */
export class RevalidateFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: RevalidateFunctionProps) {
    super(scope, id, {
      description: 'src/lambdas/revalidate/revalidate.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambdas/revalidate/revalidate.lambda')),
    });
  }
}