# ~~ Generated by cdk-nextjs ~~
# cdk-nextjs rewrites any Dockerfile carrying the line above, so that an
# upgrade does not leave a stale one behind. To own this file yourself, delete
# that line and cdk-nextjs will leave the rest of it alone.
# Modified from: https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile

# Production image, copy all the files and run next
FROM public.ecr.aws/docker/library/node:24-alpine AS runner
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

ENV NODE_ENV=production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

ARG RELATIVE_PROJECT_DIR
# The deployment root cdk-nextjs staged during `next build`: the traced assets of
# every built output, keyed by repo-root-relative path, plus cdk-nextjs's own
# request-handling server under cdk-nextjs-runtime/. Replaces `.next/standalone`.
COPY --chown=nextjs:nodejs .next/cdk-nextjs-adapter/app ./
# `.next/static` and `public` are in S3 and served by CloudFront, so they are
# deliberately not staged. They are still copied here because the server answers
# them if asked directly (e.g. a request that bypasses the CDN's routing) — the
# manifest lists `.next/static`, and the runtime lists `public` when it starts —
# and because image optimization reads the source bytes of imported images from
# disk.
COPY --chown=nextjs:nodejs .next/static ./$RELATIVE_PROJECT_DIR/.next/static
COPY --chown=nextjs:nodejs public ./$RELATIVE_PROJECT_DIR/public

USER nextjs

EXPOSE 3000

ENV PORT=3000

# cdk-nextjs's own server, staged above. It invokes the entrypoints `next build`
# produced in-process; there is no `next start` and no server.js.
# CMD will be overwritten by ECS Task Definition
ENV HOSTNAME="0.0.0.0"
CMD ["node", "cdk-nextjs-runtime/server.mjs"]
