// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm dlx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for AssetsDeploymentFunction
 */
export interface AssetsDeploymentFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambdas/assets-deployment/assets-deployment.
 */
export class AssetsDeploymentFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: AssetsDeploymentFunctionProps) {
    super(scope, id, {
      description: 'src/lambdas/assets-deployment/assets-deployment.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambdas/assets-deployment/assets-deployment.lambda')),
    });
  }
}