name: e2e-tests
on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, synchronize, reopened, labeled, unlabeled]
permissions:
  id-token: write
env:
  ENV: ${{ github.event_name == 'pull_request_target' && format('pr-{0}', github.event.number) || github.ref_name }}
jobs:
  # checks if PR was created from fork
  check-fork:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.fork && 'manual-approval' || 'auto-approve' }}
    steps:
      - run: echo "Checking if PR is from fork"

  # needed because for fork PRs, they need to be manually approved
  wait-for-approval:
    needs: [check-fork]
    runs-on: ubuntu-latest
    environment: ${{ needs.check-fork.outputs.environment }}
    steps:
      - run: echo "Workflow Approved! Starting PR Checks."

  # needed because we want ability to skip e2e tests sometimes via label
  check-if-should-run:
    needs: [wait-for-approval]
    runs-on: ubuntu-latest
    # `github.event_name == 'push'` -> will run after merge to main
    # `!contains(github.event.pull_request.labels.*.name, 'skip-e2e-tests')` -> will run when PR doesn't have label: skip-e2e-tests
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'skip-e2e-tests')) }}
    steps:
      - run: echo "Workflow should run"

  glbl-fns:
    needs: check-if-should-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          # For pull_request_target, checkout PR head instead of merge commit
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
      - uses: ./.github/actions/run-e2e-tests-on-example
        with:
          aws_account: ${{ vars.AWS_ACCOUNT }}
          example_directory: global-functions
          stack_name: ${{ env.ENV }}-glbl-fns

  glbl-cntnrs:
    needs: check-if-should-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          # For pull_request_target, checkout PR head instead of merge commit
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
      - uses: ./.github/actions/run-e2e-tests-on-example
        with:
          aws_account: ${{ vars.AWS_ACCOUNT }}
          example_directory: global-containers
          stack_name: ${{ env.ENV }}-glbl-cntnrs

  rgnl-cntnrs:
    needs: check-if-should-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          # For pull_request_target, checkout PR head instead of merge commit
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
      - uses: ./.github/actions/run-e2e-tests-on-example
        with:
          aws_account: ${{ vars.AWS_ACCOUNT }}
          example_directory: regional-containers
          stack_name: ${{ env.ENV }}-rgnl-cntnrs
