name: Setup Environment

on:
  workflow_call:
    secrets:
      AWS_ACCOUNT:
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GitHubActionRole
      - name: Build cdk-nextjs
        run: cd .. && pnpm i && pnpm bundle && pnpm compile
      - name: Install dependencies
        run: pnpm i