import { isUntouchedDockerfile, stampDockerfile } from "./nextjs-containers";

const SOURCE = "# ~~ Generated by cdk-nextjs ~~\nFROM node:24-alpine\n";

describe("generated Dockerfile stamp", () => {
  it("recognizes a stamped file nobody edited", () => {
    expect(isUntouchedDockerfile(stampDockerfile(SOURCE))).toBe(true);
  });

  it("treats an edit under the header as a change worth backing up", () => {
    const edited = stampDockerfile(SOURCE).replace(
      "FROM node:24-alpine",
      "FROM node:24-alpine\nRUN apk add curl",
    );
    expect(isUntouchedDockerfile(edited)).toBe(false);
  });

  it("treats a file from before the stamp as possibly edited", () => {
    expect(isUntouchedDockerfile(SOURCE)).toBe(false);
  });

  it("stamps a source without a trailing newline the same way", () => {
    expect(stampDockerfile(SOURCE.trimEnd())).toBe(stampDockerfile(SOURCE));
  });
});
